FROM node:20 as build

WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client/ .
RUN npm run build

# Serve using nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html