events {}

http {
    server {
        listen 80;
        server_name local.eatwisely.com;

        # FRONTEND
        location / {
            proxy_pass http://eatwisely-frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_intercept_errors on;
            error_page 404 = /index.html;
        }

        # BACKEND API
        location /api/ {
            proxy_pass http://eatwisely-backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}