export const PERMISSIONS = {
  superAdmin: {
    auth: ["signup", "signin", "google", "signout", "session", "changePassword"],
    user: [
      "test",
      "listAll",
      "listAdmins",
      "listStoreManagers",
      "createStoreManager",
      "updateAny",
      "deleteAny",
      "deactivateAny",
      "restoreAny",
      "assignStoreManager",
      "changeStoreManagerOwner",
      "unassignStoreManager",
    ],
    admin: ["createPrivilegedUser"],
    audit: ["read"],
    restaurant: [
      "create",
      "listAll",
      "readById",
      "updateAny",
      "deleteAny",
      "changeStatus",
      "restore",
      "reassignAdmin",
    ],
    category: [
      "createGeneric",
      "createScoped",
      "readAll",
      "readDeleted",
      "export",
      "bulkStatus",
      "bulkReorder",
      "reorder",
      "checkSlug",
      "updateAny",
      "updateStatusAny",
      "restore",
      "hardDelete",
      "readAudit",
      "deleteScoped",
    ],
    menu: [
      "create",
      "readById",
      "readDeleted",
      "readAudit",
      "addItem",
      "updateItem",
      "deleteItem",
      "toggleAvailability",
      "changeStatus",
      "reorderItems",
      "restore",
      "deleteSoft",
      "deleteHard",
    ],
    review: [
      "readByRestaurant",
      "readSummary",
      "readById",
      "updateAny",
      "deleteAny",
      "moderate",
    ],
    system: ["health", "live", "docs"],
  },
  admin: {
    auth: ["signout", "session", "changePassword"],
    user: [
      "listStoreManagers",
      "createStoreManager",
      "updateSelf",
      "deleteSelf",
      "deactivateSelf",
      "assignStoreManager",
      "unassignStoreManager",
    ],
    audit: ["readScoped"],
    restaurant: [
      "create",
      "readMine",
      "readMineSummary",
      "readOwnedById",
      "updateOwned",
      "deleteOwned",
    ],
    category: [
      "createScoped",
      "readMine",
      "checkSlug",
      "reorder",
      "bulkReorder",
      "readByIdScoped",
      "updateScoped",
      "updateStatusScoped",
      "deleteScoped",
      "readAuditScoped",
    ],
    menu: [
      "create",
      "readByIdScoped",
      "readDeletedScoped",
      "readAuditScoped",
      "addItem",
      "updateItem",
      "deleteItem",
      "toggleAvailability",
      "changeStatus",
      "reorderItems",
      "restoreScoped",
      "deleteSoftScoped",
    ],
    review: ["readByIdScoped", "moderateScoped"],
    system: ["health", "live", "docs"],
  },
  storeManager: {
    auth: ["signout", "session", "changePassword"],
    menu: [
      "create",
      "readByIdScoped",
      "addItem",
      "updateItem",
      "deleteItem",
      "toggleAvailability",
      "changeStatus",
      "reorderItems",
      "restoreScoped",
      "deleteSoftScoped",
    ],
    review: ["readByIdScoped"],
    system: ["health", "live", "docs"],
  },
  user: {
    auth: ["signout", "session", "changePassword"],
    review: [
      "createOwn",
      "listOwn",
      "readByIdOwn",
      "updateOwn",
      "deleteOwn",
      "readByRestaurant",
      "readSummary",
    ],
    system: ["health", "live", "docs"],
  },
};
