/* eslint-disable no-console */
/**
 * Restaurant Seed: Create 20 UK restaurants with varied featured/trending status
 */

export const run = async (db) => {
  console.log('Creating 20 restaurants...');

  const users = await db.collection('users').find({ role: 'admin' }).toArray();
  if (users.length === 0) {
    console.log('No admin user found. Please run 001_sample_users.js first.');
    return;
  }
  const adminId = users[0]._id;

  const restaurants = [
    {
      name: 'EatWisely The Ivy Garden',
      slug: 'eatwisely-the-ivy-garden',
      tagline: 'Garden to table excellence',
      description: 'A premium dining experience featuring seasonal British cuisine with ingredients sourced from our on-site kitchen garden.',
      address: {
        addressLine1: '45 Kingsway',
        addressLine2: 'Covent Garden',
        areaLocality: 'Westminster',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'WC2B 6AN',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1188, 51.5125] }
      },
      openingHours: {
        monday: { open: '08:00', close: '22:00', isClosed: false },
        tuesday: { open: '08:00', close: '22:00', isClosed: false },
        wednesday: { open: '08:00', close: '22:00', isClosed: false },
        thursday: { open: '08:00', close: '23:00', isClosed: false },
        friday: { open: '08:00', close: '23:30', isClosed: false },
        saturday: { open: '09:00', close: '23:30', isClosed: false },
        sunday: { open: '10:00', close: '21:00', isClosed: false }
      },
      contactNumber: '+442071234581',
      email: 'ivygarden@eatwisely.com',
      website: 'https://eatwisely-ivy-garden.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: true,
      isTrending: true,
      rating: 4.8,
      reviewCount: 234,
      fhrsId: 1234567,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely ivy garden premium british cuisine covent garden'
    },
    {
      name: 'EatWisely Spice Lane',
      slug: 'eatwisely-spice-lane',
      tagline: 'Authentic curries, modern flair',
      description: 'Award-winning Indian restaurant blending traditional recipes with contemporary presentation.',
      address: {
        addressLine1: '78 Brick Lane',
        addressLine2: 'Spitalfields',
        areaLocality: 'Tower Hamlets',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'E1 6RF',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.0719, 51.5196] }
      },
      openingHours: {
        monday: { open: '12:00', close: '23:00', isClosed: false },
        tuesday: { open: '12:00', close: '23:00', isClosed: false },
        wednesday: { open: '12:00', close: '23:00', isClosed: false },
        thursday: { open: '12:00', close: '23:30', isClosed: false },
        friday: { open: '12:00', close: '00:00', isClosed: false },
        saturday: { open: '12:00', close: '00:00', isClosed: false },
        sunday: { open: '13:00', close: '22:00', isClosed: false }
      },
      contactNumber: '+442071234582',
      email: 'spicelane@eatwisely.com',
      website: 'https://eatwisely-spice-lane.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: true,
      isTrending: false,
      rating: 4.6,
      reviewCount: 189,
      fhrsId: 1234568,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely spice lane indian curry brick lane'
    },
    {
      name: 'EatWisely Mediterranean Breeze',
      slug: 'eatwisely-mediterranean-breeze',
      tagline: 'Coastal flavors from the heart',
      description: 'Fresh seafood and Mediterranean classics with stunning Thames views.',
      address: {
        addressLine1: '12 Riverside Walk',
        addressLine2: 'Bankside',
        areaLocality: 'Southwark',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'SE1 9PB',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.0986, 51.5078] }
      },
      openingHours: {
        monday: { open: '11:00', close: '22:00', isClosed: false },
        tuesday: { open: '11:00', close: '22:00', isClosed: false },
        wednesday: { open: '11:00', close: '22:00', isClosed: false },
        thursday: { open: '11:00', close: '22:00', isClosed: false },
        friday: { open: '11:00', close: '23:00', isClosed: false },
        saturday: { open: '10:00', close: '23:00', isClosed: false },
        sunday: { open: '10:00', close: '21:00', isClosed: false }
      },
      contactNumber: '+442071234583',
      email: 'medbreeze@eatwisely.com',
      website: 'https://eatwisely-mediterranean.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: true,
      rating: 4.5,
      reviewCount: 156,
      fhrsId: 1234569,
      fsaRating: { value: '4', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely mediterranean breeze seafood thames southbank'
    },
    {
      name: 'EatWisely Sakura Japanese',
      slug: 'eatwisely-sakura-japanese',
      tagline: 'Precision on a plate',
      description: 'Authentic omakase experience with the finest sushi and sashimi.',
      address: {
        addressLine1: '34 Mayfair Lane',
        addressLine2: 'Mayfair',
        areaLocality: 'Westminster',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'W1K 2PQ',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1460, 51.5094] }
      },
      openingHours: {
        monday: { open: '12:00', close: '14:30', isClosed: false },
        tuesday: { open: '12:00', close: '14:30', isClosed: false },
        wednesday: { open: '12:00', close: '14:30', isClosed: false },
        thursday: { open: '12:00', close: '14:30', isClosed: false },
        friday: { open: '12:00', close: '22:30', isClosed: false },
        saturday: { open: '18:00', close: '22:30', isClosed: false },
        sunday: { open: '00:00', close: '00:00', isClosed: true }
      },
      contactNumber: '+442071234584',
      email: 'sakura@eatwisely.com',
      website: 'https://eatwisely-sakura.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: true,
      isTrending: true,
      rating: 4.9,
      reviewCount: 312,
      fhrsId: 1234570,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely sakura japanese sushi omakase mayfair'
    },
    {
      name: 'EatWisely The Burger Joint',
      slug: 'eatwisely-the-burger-joint',
      tagline: 'Crafted with passion',
      description: 'Gourmet burgers using locally sourced beef and artisanal buns.',
      address: {
        addressLine1: '56 Camden High Street',
        areaLocality: 'Camden',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'NW1 0JH',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1426, 51.5356] }
      },
      openingHours: {
        monday: { open: '11:00', close: '23:00', isClosed: false },
        tuesday: { open: '11:00', close: '23:00', isClosed: false },
        wednesday: { open: '11:00', close: '23:00', isClosed: false },
        thursday: { open: '11:00', close: '23:00', isClosed: false },
        friday: { open: '11:00', close: '00:00', isClosed: false },
        saturday: { open: '11:00', close: '00:00', isClosed: false },
        sunday: { open: '12:00', close: '22:00', isClosed: false }
      },
      contactNumber: '+442071234585',
      email: 'burgerjoint@eatwisely.com',
      website: 'https://eatwisely-burger-joint.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: true,
      rating: 4.4,
      reviewCount: 278,
      fhrsId: 1234571,
      fsaRating: { value: '4', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely burger joint gourmet burgers camden'
    },
    {
      name: 'EatWisely French Quarter',
      slug: 'eatwisely-french-quarter',
      tagline: 'Classic French elegance',
      description: 'Traditional French cuisine in an intimate setting reminiscent of a Parisian bistro.',
      address: {
        addressLine1: '89 Rue de Chelsea',
        addressLine2: 'Chelsea',
        areaLocality: 'Kensington and Chelsea',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'SW3 3RZ',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1683, 51.4875] }
      },
      openingHours: {
        monday: { open: '18:00', close: '22:30', isClosed: false },
        tuesday: { open: '18:00', close: '22:30', isClosed: false },
        wednesday: { open: '18:00', close: '22:30', isClosed: false },
        thursday: { open: '18:00', close: '23:00', isClosed: false },
        friday: { open: '18:00', close: '23:30', isClosed: false },
        saturday: { open: '12:00', close: '23:30', isClosed: false },
        sunday: { open: '12:00', close: '21:00', isClosed: false }
      },
      contactNumber: '+442071234586',
      email: 'frenchquarter@eatwisely.com',
      website: 'https://eatwisely-french-quarter.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: true,
      isTrending: false,
      rating: 4.7,
      reviewCount: 145,
      fhrsId: 1234572,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely french quarter parisian bistro chelsea'
    },
    {
      name: 'EatWisely Thai Orchid',
      slug: 'eatwisely-thai-orchid',
      tagline: 'Flavours of Bangkok',
      description: 'Authentic Thai cuisine featuring recipes passed down through generations.',
      address: {
        addressLine1: '23 Soho Square',
        areaLocality: 'Soho',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'W1D 3QF',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1320, 51.5139] }
      },
      openingHours: {
        monday: { open: '12:00', close: '22:30', isClosed: false },
        tuesday: { open: '12:00', close: '22:30', isClosed: false },
        wednesday: { open: '12:00', close: '22:30', isClosed: false },
        thursday: { open: '12:00', close: '23:00', isClosed: false },
        friday: { open: '12:00', close: '23:30', isClosed: false },
        saturday: { open: '12:00', close: '23:30', isClosed: false },
        sunday: { open: '13:00', close: '22:00', isClosed: false }
      },
      contactNumber: '+442071234587',
      email: 'thaiorchid@eatwisely.com',
      website: 'https://eatwisely-thai-orchid.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: true,
      rating: 4.5,
      reviewCount: 198,
      fhrsId: 1234573,
      fsaRating: { value: '4', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely thai orchid bangkok soho'
    },
    {
      name: 'EatWisely Steakhouse 1920',
      slug: 'eatwisely-steakhouse-1920',
      tagline: 'Where tradition meets taste',
      description: 'Classic American steakhouse experience with premium cuts and vintage ambiance.',
      address: {
        addressLine1: '150 Canary Wharf',
        addressLine2: 'Canada Square',
        areaLocality: 'Isle of Dogs',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'E14 5AB',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.0235, 51.5054] }
      },
      openingHours: {
        monday: { open: '17:00', close: '23:00', isClosed: false },
        tuesday: { open: '17:00', close: '23:00', isClosed: false },
        wednesday: { open: '17:00', close: '23:00', isClosed: false },
        thursday: { open: '17:00', close: '23:30', isClosed: false },
        friday: { open: '17:00', close: '00:00', isClosed: false },
        saturday: { open: '12:00', close: '00:00', isClosed: false },
        sunday: { open: '12:00', close: '22:00', isClosed: false }
      },
      contactNumber: '+442071234588',
      email: 'steakhouse1920@eatwisely.com',
      website: 'https://eatwisely-steakhouse-1920.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1558030006-450675393462?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: true,
      isTrending: true,
      rating: 4.6,
      reviewCount: 267,
      fhrsId: 1234574,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely steakhouse 1920 american steakhouse canary wharf'
    },
    {
      name: 'EatWisely Pizza Paradiso',
      slug: 'eatwisely-pizza-paradiso',
      tagline: 'Wood-fired perfection',
      description: 'Authentic Neapolitan pizza baked in traditional wood-fired ovens.',
      address: {
        addressLine1: '78 Portobello Road',
        areaLocality: 'Notting Hill',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'W11 2DY',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.2050, 51.5174] }
      },
      openingHours: {
        monday: { open: '12:00', close: '22:00', isClosed: false },
        tuesday: { open: '12:00', close: '22:00', isClosed: false },
        wednesday: { open: '12:00', close: '22:00', isClosed: false },
        thursday: { open: '12:00', close: '23:00', isClosed: false },
        friday: { open: '12:00', close: '23:30', isClosed: false },
        saturday: { open: '11:00', close: '23:30', isClosed: false },
        sunday: { open: '11:00', close: '21:00', isClosed: false }
      },
      contactNumber: '+442071234589',
      email: 'pizzaparadiso@eatwisely.com',
      website: 'https://eatwisely-pizza-paradiso.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: false,
      rating: 4.3,
      reviewCount: 156,
      fhrsId: 1234575,
      fsaRating: { value: '4', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely pizza paradiso neapolitan portobello notting hill'
    },
    {
      name: 'EatWisely Vietnamese Kitchen',
      slug: 'eatwisely-vietnamese-kitchen',
      tagline: 'Fresh, vibrant, wholesome',
      description: 'Modern Vietnamese cuisine with fresh herbs and bold flavours.',
      address: {
        addressLine1: '45 Greenwich Street',
        areaLocality: 'Greenwich',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'SE10 9BL',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.0041, 51.4816] }
      },
      openingHours: {
        monday: { open: '11:30', close: '21:30', isClosed: false },
        tuesday: { open: '11:30', close: '21:30', isClosed: false },
        wednesday: { open: '11:30', close: '21:30', isClosed: false },
        thursday: { open: '11:30', close: '22:00', isClosed: false },
        friday: { open: '11:30', close: '22:30', isClosed: false },
        saturday: { open: '11:00', close: '22:30', isClosed: false },
        sunday: { open: '11:00', close: '21:00', isClosed: false }
      },
      contactNumber: '+442071234590',
      email: 'vietkitchen@eatwisely.com',
      website: 'https://eatwisely-vietnamese-kitchen.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: false,
      rating: 4.4,
      reviewCount: 134,
      fhrsId: 1234576,
      fsaRating: { value: '4', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely vietnamese kitchen pho greenwich'
    },
    {
      name: 'EatWisely Rooftop Grill',
      slug: 'eatwisely-rooftop-grill',
      tagline: 'Sky-high dining',
      description: 'Contemporary grill with panoramic city views and innovative cocktails.',
      address: {
        addressLine1: '30 The Shard',
        addressLine2: 'London Bridge',
        areaLocality: 'Southwark',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'SE1 9SG',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.0865, 51.5045] }
      },
      openingHours: {
        monday: { open: '17:00', close: '23:00', isClosed: false },
        tuesday: { open: '17:00', close: '23:00', isClosed: false },
        wednesday: { open: '17:00', close: '23:00', isClosed: false },
        thursday: { open: '17:00', close: '00:00', isClosed: false },
        friday: { open: '17:00', close: '01:00', isClosed: false },
        saturday: { open: '12:00', close: '01:00', isClosed: false },
        sunday: { open: '12:00', close: '22:00', isClosed: false }
      },
      contactNumber: '+442071234591',
      email: 'rooftopgrill@eatwisely.com',
      website: 'https://eatwisely-rooftop-grill.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: true,
      isTrending: true,
      rating: 4.8,
      reviewCount: 423,
      fhrsId: 1234577,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely rooftop grill views shard london bridge'
    },
    {
      name: 'EatWisely Greek Taverna',
      slug: 'eatwisely-greek-taverna',
      tagline: 'Mediterranean warmth',
      description: 'Traditional Greek cuisine with mezze platters and grilled specialities.',
      address: {
        addressLine1: '67 Exmouth Market',
        areaLocality: 'Clerkenwell',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'EC1R 4QL',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1118, 51.5250] }
      },
      openingHours: {
        monday: { open: '12:00', close: '22:00', isClosed: false },
        tuesday: { open: '12:00', close: '22:00', isClosed: false },
        wednesday: { open: '12:00', close: '22:00', isClosed: false },
        thursday: { open: '12:00', close: '23:00', isClosed: false },
        friday: { open: '12:00', close: '23:30', isClosed: false },
        saturday: { open: '12:00', close: '23:30', isClosed: false },
        sunday: { open: '13:00', close: '21:00', isClosed: false }
      },
      contactNumber: '+442071234592',
      email: 'greektaverna@eatwisely.com',
      website: 'https://eatwisely-greek-taverna.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: false,
      rating: 4.5,
      reviewCount: 167,
      fhrsId: 1234578,
      fsaRating: { value: '4', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely greek taverna mezze clerkenwell exmouth market'
    },
    {
      name: 'EatWisely Seoul Kitchen',
      slug: 'eatwisely-seoul-kitchen',
      tagline: 'Korean BBQ at its finest',
      description: 'Interactive Korean BBQ dining with premium meats and traditional sides.',
      address: {
        addressLine1: '88 New Malden High Street',
        areaLocality: 'New Malden',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'KT3 4ND',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.2569, 51.4084] }
      },
      openingHours: {
        monday: { open: '17:00', close: '22:30', isClosed: false },
        tuesday: { open: '17:00', close: '22:30', isClosed: false },
        wednesday: { open: '17:00', close: '22:30', isClosed: false },
        thursday: { open: '17:00', close: '23:00', isClosed: false },
        friday: { open: '17:00', close: '23:30', isClosed: false },
        saturday: { open: '12:00', close: '23:30', isClosed: false },
        sunday: { open: '12:00', close: '22:00', isClosed: false }
      },
      contactNumber: '+442071234593',
      email: 'seoulkitchen@eatwisely.com',
      website: 'https://eatwisely-seoul-kitchen.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: true,
      rating: 4.6,
      reviewCount: 289,
      fhrsId: 1234579,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely seoul kitchen korean bbq new malden'
    },
    {
      name: 'EatWisely Plant Power',
      slug: 'eatwisely-plant-power',
      tagline: 'Vegan fine dining',
      description: 'Award-winning plant-based cuisine that challenges perceptions of vegan food.',
      address: {
        addressLine1: '12 Shoreditch High Street',
        areaLocality: 'Shoreditch',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'E1 6PG',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.0774, 51.5244] }
      },
      openingHours: {
        monday: { open: '12:00', close: '21:00', isClosed: false },
        tuesday: { open: '12:00', close: '21:00', isClosed: false },
        wednesday: { open: '12:00', close: '21:00', isClosed: false },
        thursday: { open: '12:00', close: '22:00', isClosed: false },
        friday: { open: '12:00', close: '22:30', isClosed: false },
        saturday: { open: '10:00', close: '22:30', isClosed: false },
        sunday: { open: '10:00', close: '20:00', isClosed: false }
      },
      contactNumber: '+442071234594',
      email: 'plantpower@eatwisely.com',
      website: 'https://eatwisely-plant-power.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1540914124281-342587941389?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: true,
      isTrending: false,
      rating: 4.7,
      reviewCount: 312,
      fhrsId: 1234580,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely plant power vegan fine dining shoreditch'
    },
    {
      name: 'EatWisely Fish & Chips',
      slug: 'eatwisely-fish-and-chips',
      tagline: 'British seaside tradition',
      description: 'Premium fish and chips using sustainable fish and triple-cooked chips.',
      address: {
        addressLine1: '201 Baker Street',
        areaLocality: 'Marylebone',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'NW1 6XE',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1575, 51.5226] }
      },
      openingHours: {
        monday: { open: '11:00', close: '21:00', isClosed: false },
        tuesday: { open: '11:00', close: '21:00', isClosed: false },
        wednesday: { open: '11:00', close: '21:00', isClosed: false },
        thursday: { open: '11:00', close: '22:00', isClosed: false },
        friday: { open: '11:00', close: '22:30', isClosed: false },
        saturday: { open: '11:00', close: '22:30', isClosed: false },
        sunday: { open: '12:00', close: '20:00', isClosed: false }
      },
      contactNumber: '+442071234595',
      email: 'fishandchips@eatwisely.com',
      website: 'https://eatwisely-fish-chips.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1579208030886-b937da0925dc?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1579208570378-8c970854bc23?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: false,
      rating: 4.3,
      reviewCount: 198,
      fhrsId: 1234581,
      fsaRating: { value: '4', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely fish chips marylebone baker street'
    },
    {
      name: 'EatWisely Tapas Revolution',
      slug: 'eatwisely-tapas-revolution',
      tagline: 'Small plates, big flavours',
      description: 'Contemporary Spanish tapas with an innovative twist on classic recipes.',
      address: {
        addressLine1: '55 Brixton Village',
        areaLocality: 'Brixton',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'SW9 8PR',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1140, 51.4615] }
      },
      openingHours: {
        monday: { open: '17:00', close: '23:00', isClosed: false },
        tuesday: { open: '17:00', close: '23:00', isClosed: false },
        wednesday: { open: '17:00', close: '23:00', isClosed: false },
        thursday: { open: '17:00', close: '23:30', isClosed: false },
        friday: { open: '17:00', close: '00:00', isClosed: false },
        saturday: { open: '12:00', close: '00:00', isClosed: false },
        sunday: { open: '12:00', close: '22:00', isClosed: false }
      },
      contactNumber: '+442071234596',
      email: 'tapasrevolution@eatwisely.com',
      website: 'https://eatwisely-tapas-revolution.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: true,
      rating: 4.5,
      reviewCount: 234,
      fhrsId: 1234582,
      fsaRating: { value: '4', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely tapas revolution spanish brixton village'
    },
    {
      name: 'EatWisely Dim Sum House',
      slug: 'eatwisely-dim-sum-house',
      tagline: 'Hong Kong tradition',
      description: 'Authentic dim sum served from traditional bamboo steamers.',
      address: {
        addressLine1: '8 Gerrard Place',
        areaLocality: 'Soho',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'W1D 5PH',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1281, 51.5107] }
      },
      openingHours: {
        monday: { open: '11:00', close: '21:30', isClosed: false },
        tuesday: { open: '11:00', close: '21:30', isClosed: false },
        wednesday: { open: '11:00', close: '21:30', isClosed: false },
        thursday: { open: '11:00', close: '22:00', isClosed: false },
        friday: { open: '11:00', close: '22:30', isClosed: false },
        saturday: { open: '10:00', close: '22:30', isClosed: false },
        sunday: { open: '10:00', close: '21:00', isClosed: false }
      },
      contactNumber: '+442071234597',
      email: 'dimsumhouse@eatwisely.com',
      website: 'https://eatwisely-dim-sum-house.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: false,
      rating: 4.4,
      reviewCount: 187,
      fhrsId: 1234583,
      fsaRating: { value: '4', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely dim sum house chinese soho gerard place'
    },
    {
      name: 'EatWisely Brunch Social',
      slug: 'eatwisely-brunch-social',
      tagline: 'Morning rituals reimagined',
      description: 'All-day brunch with inventive dishes and specialty coffee.',
      address: {
        addressLine1: '34 Columbia Road',
        areaLocality: 'Bethnal Green',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'E2 7RG',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.0714, 51.5284] }
      },
      openingHours: {
        monday: { open: '08:00', close: '16:00', isClosed: false },
        tuesday: { open: '08:00', close: '16:00', isClosed: false },
        wednesday: { open: '08:00', close: '16:00', isClosed: false },
        thursday: { open: '08:00', close: '16:00', isClosed: false },
        friday: { open: '08:00', close: '17:00', isClosed: false },
        saturday: { open: '09:00', close: '17:00', isClosed: false },
        sunday: { open: '09:00', close: '15:00', isClosed: false }
      },
      contactNumber: '+442071234598',
      email: 'brunchsocial@eatwisely.com',
      website: 'https://eatwisely-brunch-social.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: true,
      rating: 4.6,
      reviewCount: 256,
      fhrsId: 1234584,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely brunch social all day breakfast columbia road bethnal green'
    },
    {
      name: 'EatWisely The Wine Cellar',
      slug: 'eatwisely-the-wine-cellar',
      tagline: 'Dine beneath the city',
      description: 'Intimate underground dining with sommelier-curated wine pairings.',
      address: {
        addressLine1: '-1 Chancery Lane',
        areaLocality: 'Holborn',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'WC2A 1PL',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1115, 51.5180] }
      },
      openingHours: {
        monday: { open: '18:00', close: '22:30', isClosed: false },
        tuesday: { open: '18:00', close: '22:30', isClosed: false },
        wednesday: { open: '18:00', close: '22:30', isClosed: false },
        thursday: { open: '18:00', close: '23:00', isClosed: false },
        friday: { open: '18:00', close: '23:30', isClosed: false },
        saturday: { open: '17:00', close: '23:30', isClosed: false },
        sunday: { open: '00:00', close: '00:00', isClosed: true }
      },
      contactNumber: '+442071234599',
      email: 'winecellar@eatwisely.com',
      website: 'https://eatwisely-wine-cellar.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: true,
      isTrending: false,
      rating: 4.8,
      reviewCount: 178,
      fhrsId: 1234585,
      fsaRating: { value: '5', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely wine cellar underground dining holborn'
    },
    {
      name: 'EatWisely Burger Barn',
      slug: 'eatwisely-burger-barn',
      tagline: 'American comfort food',
      description: 'Loaded burgers, loaded fries, and hand-spun milkshakes.',
      address: {
        addressLine1: '120 Streatham High Road',
        areaLocality: 'Streatham',
        city: 'London',
        countyRegion: 'Greater London',
        postcode: 'SW16 6BW',
        country: 'United Kingdom',
        location: { type: 'Point', coordinates: [-0.1295, 51.4279] }
      },
      openingHours: {
        monday: { open: '12:00', close: '22:00', isClosed: false },
        tuesday: { open: '12:00', close: '22:00', isClosed: false },
        wednesday: { open: '12:00', close: '22:00', isClosed: false },
        thursday: { open: '12:00', close: '23:00', isClosed: false },
        friday: { open: '12:00', close: '00:00', isClosed: false },
        saturday: { open: '12:00', close: '00:00', isClosed: false },
        sunday: { open: '13:00', close: '21:00', isClosed: false }
      },
      contactNumber: '+442071234600',
      email: 'burgerbarn@eatwisely.com',
      website: 'https://eatwisely-burger-barn.co.uk',
      imageLogo: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400',
      bannerImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200',
      adminId,
      status: 'published',
      isActive: true,
      isFeatured: false,
      isTrending: false,
      rating: 4.2,
      reviewCount: 145,
      fhrsId: 1234586,
      fsaRating: { value: '3', lastRefreshed: new Date(), isManuallyLinked: true },
      searchText: 'eatwisely burger barn loaded burgers streatham'
    }
  ];

  let insertedCount = 0;
  for (const restaurant of restaurants) {
    await db.collection('restaurants').updateOne(
      { slug: restaurant.slug },
      { $setOnInsert: restaurant },
      { upsert: true }
    );
    insertedCount++;
  }

  console.log(`Processed ${insertedCount} restaurants`);
  console.log('\nFeatured restaurants:', restaurants.filter(r => r.isFeatured).length);
  console.log('Trending restaurants:', restaurants.filter(r => r.isTrending).length);
  console.log('Both featured & trending:', restaurants.filter(r => r.isFeatured && r.isTrending).length);
};
